# Generated by Django 3.1.6 on 2021-02-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_comment_comment_author_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_author_email',
            field=models.EmailField(max_length=254),
        ),
    ]
